openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: EC2 Image Builder CancelImageCreation List Distribution Configurations API
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: imagebuilder
  x-aws-signingName: imagebuilder
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/imagebuilder-2019-12-02.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The imagebuilder multi-region endpoint
- url: https://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The imagebuilder multi-region endpoint
- url: http://imagebuilder.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The imagebuilder endpoint for China (Beijing) and China (Ningxia)
- url: https://imagebuilder.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The imagebuilder endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: ListDistributionConfigurations
paths:
  /ListDistributionConfigurations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListDistributionConfigurations
      description: Returns a list of distribution configurations.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDistributionConfigurationsResponse'
              examples:
                ListDistributionConfigurations200Example:
                  summary: Default ListDistributionConfigurations 200 response
                  x-microcks-default: true
                  value:
                    requestId: example-id-1234
                    distributionConfigurationSummaryList: example-string
                    nextToken: example-string
        '480':
          description: ServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceException'
              examples:
                ListDistributionConfigurations480Example:
                  summary: Default ListDistributionConfigurations 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ClientException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientException'
              examples:
                ListDistributionConfigurations481Example:
                  summary: Default ListDistributionConfigurations 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
        '483':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '484':
          description: InvalidPaginationTokenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidPaginationTokenException'
        '485':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
        '486':
          description: CallRateLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallRateLimitExceededException'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  description: You can filter on <code>name</code> to streamline results.
                  type: array
                  items:
                    $ref: '#/components/schemas/Filter'
                  minItems: 1
                  maxItems: 10
                maxResults:
                  description: The maximum items to return in a request.
                  type: integer
                  minimum: 1
                  maximum: 25
                nextToken:
                  description: A token to specify where to start paginating. This is the NextToken from a previously truncated response.
                  type: string
                  minLength: 1
                  maxLength: 65535
      summary: Amazon EC2 Image Builder List Distribution Configurations
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - ListDistributionConfigurations
components:
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    Filter:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/FilterName'
          - description: The name of the filter. Filter names are case-sensitive.
        values:
          allOf:
          - $ref: '#/components/schemas/FilterValues'
          - description: The filter values. Filter values are case-sensitive.
      description: A filter name and value pair that is used to return a more specific list of results from a list operation. Filters can be used to match a set of resources by specific criteria, such as tags, attributes, or IDs.
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 1024
    ServiceUnavailableException: {}
    ClientException: {}
    ListDistributionConfigurationsResponse:
      type: object
      properties:
        requestId:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The request ID that uniquely identifies this request.
        distributionConfigurationSummaryList:
          allOf:
          - $ref: '#/components/schemas/DistributionConfigurationSummaryList'
          - description: The list of distributions.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: The next token used for paginated responses. When this field isn't empty, there are additional elements that the service has'ot included in this request. Use this token with the next request to retrieve additional objects.
    PaginationToken:
      type: string
      minLength: 1
      maxLength: 65535
    InvalidPaginationTokenException: {}
    InvalidRequestException: {}
    ServiceException: {}
    ResourceName:
      type: string
      pattern: ^[-_A-Za-z-0-9][-_A-Za-z0-9 ]{1,126}[-_A-Za-z-0-9]$
    DateTime:
      type: string
    FilterName:
      type: string
      pattern: ^[a-zA-Z]{1,1024}$
    ForbiddenException: {}
    TagMap:
      type: object
      minProperties: 1
      maxProperties: 50
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    CallRateLimitExceededException: {}
    ImageBuilderArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):(?:image-recipe|container-recipe|infrastructure-configuration|distribution-configuration|component|image|image-pipeline|workflow\/(?:build|test|distribution))/[a-z0-9-_]+(?:/(?:(?:x|[0-9]+)\.(?:x|[0-9]+)\.(?:x|[0-9]+))(?:/[0-9]+)?)?$
    DistributionConfigurationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/DistributionConfigurationSummary'
    TagValue:
      type: string
      maxLength: 256
    DistributionConfigurationSummary:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/ImageBuilderArn'
          - description: The Amazon Resource Name (ARN) of the distribution configuration.
        name:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the distribution configuration.
        description:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The description of the distribution configuration.
        dateCreated:
          allOf:
          - $ref: '#/components/schemas/DateTime'
          - description: The date on which the distribution configuration was created.
        dateUpdated:
          allOf:
          - $ref: '#/components/schemas/DateTime'
          - description: The date on which the distribution configuration was updated.
        tags:
          allOf:
          - $ref: '#/components/schemas/TagMap'
          - description: The tags associated with the distribution configuration.
        regions:
          allOf:
          - $ref: '#/components/schemas/RegionList'
          - description: A list of Regions where the container image is distributed to.
      description: A high-level overview of a distribution configuration.
    RegionList:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
    FilterValue:
      type: string
      pattern: ^[0-9a-zA-Z./_ :-]{1,1024}$
    FilterValues:
      type: array
      items:
        $ref: '#/components/schemas/FilterValue'
      minItems: 1
      maxItems: 10
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/imagebuilder/
x-hasEquivalentPaths: true
