openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: EC2 Image Builder CancelImageCreation Create Image API
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: imagebuilder
  x-aws-signingName: imagebuilder
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/imagebuilder-2019-12-02.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The imagebuilder multi-region endpoint
- url: https://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The imagebuilder multi-region endpoint
- url: http://imagebuilder.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The imagebuilder endpoint for China (Beijing) and China (Ningxia)
- url: https://imagebuilder.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The imagebuilder endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: CreateImage
paths:
  /CreateImage:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    put:
      operationId: CreateImage
      description: Creates a new image. This request will create a new image along with all of the configured output resources defined in the distribution configuration. You must specify exactly one recipe for your image, using either a ContainerRecipeArn or an ImageRecipeArn.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateImageResponse'
              examples:
                CreateImage200Example:
                  summary: Default CreateImage 200 response
                  x-microcks-default: true
                  value:
                    requestId: example-id-1234
                    clientToken: example-string
                    imageBuildVersionArn: arn:aws:service:us-east-1:123456789012:resource/example
        '480':
          description: ServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceException'
              examples:
                CreateImage480Example:
                  summary: Default CreateImage 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ClientException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientException'
              examples:
                CreateImage481Example:
                  summary: Default CreateImage 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
        '483':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '484':
          description: IdempotentParameterMismatchException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdempotentParameterMismatchException'
        '485':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
        '486':
          description: CallRateLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallRateLimitExceededException'
        '487':
          description: ResourceInUseException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceInUseException'
        '488':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - infrastructureConfigurationArn
              - clientToken
              properties:
                imageRecipeArn:
                  description: The Amazon Resource Name (ARN) of the image recipe that defines how images are configured, tested, and assessed.
                  type: string
                  pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):image-recipe/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+$
                containerRecipeArn:
                  description: The Amazon Resource Name (ARN) of the container recipe that defines how images are configured and tested.
                  type: string
                  pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):container-recipe/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+$
                distributionConfigurationArn:
                  description: The Amazon Resource Name (ARN) of the distribution configuration that defines and configures the outputs of your pipeline.
                  type: string
                  pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):distribution-configuration/[a-z0-9-_]+$
                infrastructureConfigurationArn:
                  description: The Amazon Resource Name (ARN) of the infrastructure configuration that defines the environment in which your image will be built and tested.
                  type: string
                  pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):infrastructure-configuration/[a-z0-9-_]+$
                imageTestsConfiguration:
                  description: Configure image tests for your pipeline build. Tests run after building the image, to verify that the AMI or container image is valid before distributing it.
                  type: object
                  properties:
                    imageTestsEnabled:
                      allOf:
                      - $ref: '#/components/schemas/NullableBoolean'
                      - description: Determines if tests should run after building the image. Image Builder defaults to enable tests to run following the image build, before image distribution.
                    timeoutMinutes:
                      allOf:
                      - $ref: '#/components/schemas/ImageTestsTimeoutMinutes'
                      - description: <p>The maximum time in minutes that tests are permitted to run.</p> <note> <p>The timeoutMinutes attribute is not currently active. This value is ignored.</p> </note>
                enhancedImageMetadataEnabled:
                  description: Collects additional information about the image being created, including the operating system (OS) version and package list. This information is used to enhance the overall experience of using EC2 Image Builder. Enabled by default.
                  type: boolean
                tags:
                  description: The tags of the image.
                  type: object
                  minProperties: 1
                  maxProperties: 50
                  additionalProperties:
                    $ref: '#/components/schemas/TagValue'
                clientToken:
                  description: The idempotency token used to make this request idempotent.
                  type: string
                  minLength: 1
                  maxLength: 36
                imageScanningConfiguration:
                  description: Contains settings for Image Builder image resource and container image scans.
                  type: object
                  properties:
                    imageScanningEnabled:
                      allOf:
                      - $ref: '#/components/schemas/NullableBoolean'
                      - description: A setting that indicates whether Image Builder keeps a snapshot of the vulnerability scans that Amazon Inspector runs against the build instance when you create a new image.
                    ecrConfiguration:
                      allOf:
                      - $ref: '#/components/schemas/EcrConfiguration'
                      - description: Contains Amazon ECR settings for vulnerability scans.
      summary: Amazon EC2 Image Builder Create Image
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - CreateImage
components:
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    ServiceQuotaExceededException: {}
    IdempotentParameterMismatchException: {}
    NullableBoolean:
      type: boolean
    EcrConfiguration:
      type: object
      properties:
        repositoryName:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The name of the container repository that Amazon Inspector scans to identify findings for your container images. The name includes the path for the repository location. If you don’t provide this information, Image Builder creates a repository in your account named <code>image-builder-image-scanning-repository</code> for vulnerability scans of your output container images.
          example: example-resource-name
        containerTags:
          allOf:
          - $ref: '#/components/schemas/StringList'
          - description: Tags for Image Builder to apply to the output container image that &amp;INS; scans. Tags can help you identify and manage your scanned images.
          example: example-string
      description: Settings that Image Builder uses to configure the ECR repository and the output container images that Amazon Inspector scans.
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 1024
    CreateImageResponse:
      type: object
      properties:
        requestId:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The request ID that uniquely identifies this request.
          example: example-id-1234
        clientToken:
          allOf:
          - $ref: '#/components/schemas/ClientToken'
          - description: The idempotency token used to make this request idempotent.
          example: example-string
        imageBuildVersionArn:
          allOf:
          - $ref: '#/components/schemas/ImageBuildVersionArn'
          - description: The Amazon Resource Name (ARN) of the image that this request created.
          example: arn:aws:service:us-east-1:123456789012:resource/example
    ServiceUnavailableException: {}
    ClientException: {}
    ImageBuildVersionArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):image/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$
    ImageTestsTimeoutMinutes:
      type: integer
      minimum: 60
      maximum: 1440
    ResourceInUseException: {}
    InvalidRequestException: {}
    ServiceException: {}
    ForbiddenException: {}
    ClientToken:
      type: string
      minLength: 1
      maxLength: 36
    CallRateLimitExceededException: {}
    TagValue:
      type: string
      maxLength: 256
    StringList:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/imagebuilder/
x-hasEquivalentPaths: true
