openapi: 3.0.0
info:
  version: 2019-12-02
  x-release: v4
  title: EC2 Image Builder CancelImageCreation ListComponentBuildVersions API
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: imagebuilder
  x-aws-signingName: imagebuilder
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/imagebuilder-2019-12-02.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The imagebuilder multi-region endpoint
- url: https://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The imagebuilder multi-region endpoint
- url: http://imagebuilder.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The imagebuilder endpoint for China (Beijing) and China (Ningxia)
- url: https://imagebuilder.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The imagebuilder endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: ListComponentBuildVersions
paths:
  /ListComponentBuildVersions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListComponentBuildVersions
      description: '<p>Returns the list of component build versions for the specified semantic version.</p> <note> <p>The semantic version has four nodes: &lt;major&gt;.&lt;minor&gt;.&lt;patch&gt;/&lt;build&gt;. You can assign values for the first three, and can filter on all of them.</p> <p> <b>Filtering:</b> With semantic versioning, you have the flexibility to use wildcards (x) to specify the most recent versions or nodes when selecting the base image or components for your recipe. When you use a wildcard in any node, all nodes to the right of the first wildcard must also be wildcards.</p> </note>'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListComponentBuildVersionsResponse'
              examples:
                ListComponentBuildVersions200Example:
                  summary: Default ListComponentBuildVersions 200 response
                  x-microcks-default: true
                  value:
                    requestId: example-id-1234
                    componentSummaryList: example-string
                    nextToken: example-string
        '480':
          description: ServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceException'
              examples:
                ListComponentBuildVersions480Example:
                  summary: Default ListComponentBuildVersions 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ClientException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientException'
              examples:
                ListComponentBuildVersions481Example:
                  summary: Default ListComponentBuildVersions 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
        '483':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '484':
          description: InvalidPaginationTokenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidPaginationTokenException'
        '485':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
        '486':
          description: CallRateLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallRateLimitExceededException'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - componentVersionArn
              properties:
                componentVersionArn:
                  description: The component version Amazon Resource Name (ARN) whose versions you want to list.
                  type: string
                  pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):component/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+$
                maxResults:
                  description: The maximum items to return in a request.
                  type: integer
                  minimum: 1
                  maximum: 25
                nextToken:
                  description: A token to specify where to start paginating. This is the NextToken from a previously truncated response.
                  type: string
                  minLength: 1
                  maxLength: 65535
      summary: Amazon EC2 Image Builder List Component Build Versions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - ListComponentBuildVersions
components:
  schemas:
    Platform:
      type: string
      enum:
      - Windows
      - Linux
    OsVersion:
      type: string
      minLength: 1
    VersionNumber:
      type: string
      pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 1024
    ServiceException: {}
    DateTime:
      type: string
    ForbiddenException: {}
    ComponentType:
      type: string
      enum:
      - BUILD
      - TEST
    ServiceUnavailableException: {}
    PaginationToken:
      type: string
      minLength: 1
      maxLength: 65535
    OsVersionList:
      type: array
      items:
        $ref: '#/components/schemas/OsVersion'
      minItems: 1
      maxItems: 25
    ResourceName:
      type: string
      pattern: ^[-_A-Za-z-0-9][-_A-Za-z0-9 ]{1,126}[-_A-Za-z-0-9]$
    ComponentSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentSummary'
    Boolean:
      type: boolean
    ComponentSummary:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/ImageBuilderArn'
          - description: The Amazon Resource Name (ARN) of the component.
        name:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of the component.
        version:
          allOf:
          - $ref: '#/components/schemas/VersionNumber'
          - description: The version of the component.
        platform:
          allOf:
          - $ref: '#/components/schemas/Platform'
          - description: The operating system platform of the component.
        supportedOsVersions:
          allOf:
          - $ref: '#/components/schemas/OsVersionList'
          - description: The operating system (OS) version that the component supports. If the OS information is available, Image Builder performs a prefix match against the base image OS version during image recipe creation.
        state:
          allOf:
          - $ref: '#/components/schemas/ComponentState'
          - description: Describes the current status of the component.
        type:
          allOf:
          - $ref: '#/components/schemas/ComponentType'
          - description: The component type specifies whether Image Builder uses the component to build the image or only to test it.
        owner:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The owner of the component.
        description:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The description of the component.
        changeDescription:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The change description for the current version of the component.
        dateCreated:
          allOf:
          - $ref: '#/components/schemas/DateTime'
          - description: The original creation date of the component.
        tags:
          allOf:
          - $ref: '#/components/schemas/TagMap'
          - description: The tags that apply to the component.
        publisher:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: Contains the name of the publisher if this is a third-party component. Otherwise, this property is empty.
        obfuscate:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: Indicates whether component source is hidden from view in the console, and from component detail results for API, CLI, or SDK operations.
      description: A high-level summary of a component.
    TagMap:
      type: object
      minProperties: 1
      maxProperties: 50
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      maxLength: 256
    CallRateLimitExceededException: {}
    ComponentStatus:
      type: string
      enum:
      - DEPRECATED
    ClientException: {}
    InvalidRequestException: {}
    InvalidPaginationTokenException: {}
    ListComponentBuildVersionsResponse:
      type: object
      properties:
        requestId:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The request ID that uniquely identifies this request.
        componentSummaryList:
          allOf:
          - $ref: '#/components/schemas/ComponentSummaryList'
          - description: The list of component summaries for the specified semantic version.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: The next token used for paginated responses. When this field isn't empty, there are additional elements that the service has'ot included in this request. Use this token with the next request to retrieve additional objects.
    ComponentState:
      type: object
      properties:
        status:
          allOf:
          - $ref: '#/components/schemas/ComponentStatus'
          - description: The current state of the component.
        reason:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: Describes how or why the component changed state.
      description: A group of fields that describe the current status of components that are no longer active.
    ImageBuilderArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):(?:image-recipe|container-recipe|infrastructure-configuration|distribution-configuration|component|image|image-pipeline|workflow\/(?:build|test|distribution))/[a-z0-9-_]+(?:/(?:(?:x|[0-9]+)\.(?:x|[0-9]+)\.(?:x|[0-9]+))(?:/[0-9]+)?)?$
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/imagebuilder/
x-hasEquivalentPaths: true
