openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: EC2 Image Builder CancelImageCreation List Images API
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: imagebuilder
  x-aws-signingName: imagebuilder
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/imagebuilder-2019-12-02.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The imagebuilder multi-region endpoint
- url: https://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The imagebuilder multi-region endpoint
- url: http://imagebuilder.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The imagebuilder endpoint for China (Beijing) and China (Ningxia)
- url: https://imagebuilder.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The imagebuilder endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: ListImages
paths:
  /ListImages:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListImages
      description: Returns the list of images that you have access to. Newly created images can take up to two minutes to appear in the ListImages API Results.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListImagesResponse'
              examples:
                ListImages200Example:
                  summary: Default ListImages 200 response
                  x-microcks-default: true
                  value:
                    requestId: example-id-1234
                    imageVersionList: example-string
                    nextToken: example-string
        '480':
          description: ServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceException'
              examples:
                ListImages480Example:
                  summary: Default ListImages 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ClientException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientException'
              examples:
                ListImages481Example:
                  summary: Default ListImages 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
        '483':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '484':
          description: InvalidPaginationTokenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidPaginationTokenException'
        '485':
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenException'
        '486':
          description: CallRateLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallRateLimitExceededException'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  description: The owner defines which images you want to list. By default, this request will only show images owned by your account. You can use this field to specify if you want to view images owned by yourself, by Amazon, or those images that have been shared with you by other customers.
                  type: string
                  enum:
                  - Self
                  - Shared
                  - Amazon
                  - ThirdParty
                filters:
                  description: <p>Use the following filters to streamline results:</p> <ul> <li> <p> <code>name</code> </p> </li> <li> <p> <code>osVersion</code> </p> </li> <li> <p> <code>platform</code> </p> </li> <li> <p> <code>type</code> </p> </li> <li> <p> <code>version</code> </p> </li> </ul>
                  type: array
                  items:
                    $ref: '#/components/schemas/Filter'
                  minItems: 1
                  maxItems: 10
                byName:
                  description: Requests a list of images with a specific recipe name.
                  type: boolean
                maxResults:
                  description: The maximum items to return in a request.
                  type: integer
                  minimum: 1
                  maximum: 25
                nextToken:
                  description: A token to specify where to start paginating. This is the NextToken from a previously truncated response.
                  type: string
                  minLength: 1
                  maxLength: 65535
                includeDeprecated:
                  description: Includes deprecated images in the response list.
                  type: boolean
      summary: Amazon EC2 Image Builder List Images
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - ListImages
components:
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    Filter:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/FilterName'
          - description: The name of the filter. Filter names are case-sensitive.
        values:
          allOf:
          - $ref: '#/components/schemas/FilterValues'
          - description: The filter values. Filter values are case-sensitive.
      description: A filter name and value pair that is used to return a more specific list of results from a list operation. Filters can be used to match a set of resources by specific criteria, such as tags, attributes, or IDs.
    BuildType:
      type: string
      enum:
      - USER_INITIATED
      - SCHEDULED
      - IMPORT
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 1024
    ImageSource:
      type: string
      enum:
      - AMAZON_MANAGED
      - AWS_MARKETPLACE
      - IMPORTED
      - CUSTOM
    ServiceUnavailableException: {}
    ClientException: {}
    ImageVersionList:
      type: array
      items:
        $ref: '#/components/schemas/ImageVersion'
    PaginationToken:
      type: string
      minLength: 1
      maxLength: 65535
    InvalidPaginationTokenException: {}
    InvalidRequestException: {}
    ServiceException: {}
    ResourceName:
      type: string
      pattern: ^[-_A-Za-z-0-9][-_A-Za-z0-9 ]{1,126}[-_A-Za-z-0-9]$
    ListImagesResponse:
      type: object
      properties:
        requestId:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The request ID that uniquely identifies this request.
        imageVersionList:
          allOf:
          - $ref: '#/components/schemas/ImageVersionList'
          - description: '<p>The list of image semantic versions.</p> <note> <p>The semantic version has four nodes: &lt;major&gt;.&lt;minor&gt;.&lt;patch&gt;/&lt;build&gt;. You can assign values for the first three, and can filter on all of them.</p> <p> <b>Filtering:</b> With semantic versioning, you have the flexibility to use wildcards (x) to specify the most recent versions or nodes when selecting the base image or components for your recipe. When you use a wildcard in any node, all nodes to the right of the first wildcard must also be wildcards.</p> </note>'
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: The next token used for paginated responses. When this field isn't empty, there are additional elements that the service has'ot included in this request. Use this token with the next request to retrieve additional objects.
    DateTime:
      type: string
    FilterName:
      type: string
      pattern: ^[a-zA-Z]{1,1024}$
    ImageVersion:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/ImageBuilderArn'
          - description: '<p>The Amazon Resource Name (ARN) of a specific version of an Image Builder image.</p> <note> <p>Semantic versioning is included in each object''s Amazon Resource Name (ARN), at the level that applies to that object as follows:</p> <ol> <li> <p>Versionless ARNs and Name ARNs do not include specific values in any of the nodes. The nodes are either left off entirely, or they are specified as wildcards, for example: x.x.x.</p> </li> <li> <p>Version ARNs have only the first three nodes: &lt;major&gt;.&lt;minor&gt;.&lt;patch&gt;</p> </li> <li> <p>Build version ARNs have all four nodes, and point to a specific build for a specific version of an object.</p> </li> </ol> </note>'
        name:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The name of this specific version of an Image Builder image.
        type:
          allOf:
          - $ref: '#/components/schemas/ImageType'
          - description: Specifies whether this image produces an AMI or a container image.
        version:
          allOf:
          - $ref: '#/components/schemas/VersionNumber'
          - description: '<p>Details for a specific version of an Image Builder image. This version follows the semantic version syntax.</p> <note> <p>The semantic version has four nodes: &lt;major&gt;.&lt;minor&gt;.&lt;patch&gt;/&lt;build&gt;. You can assign values for the first three, and can filter on all of them.</p> <p> <b>Assignment:</b> For the first three nodes you can assign any positive integer value, including zero, with an upper limit of 2^30-1, or 1073741823 for each node. Image Builder automatically assigns the build number to the fourth node.</p> <p> <b>Patterns:</b> You can use any numeric pattern that adheres to the assignment requirements for the nodes that you can assign. For example, you might choose a software version pattern, such as 1.0.0, or a date, such as 2021.01.01.</p> <p> <b>Filtering:</b> With semantic versioning, you have the flexibility to use wildcards (x) to specify the most recent versions or nodes when selecting the base image or components for your recipe. When you use a wildcard in any node, all nodes to the right of the first wildcard must also be wildcards.</p> </note>'
        platform:
          allOf:
          - $ref: '#/components/schemas/Platform'
          - description: The operating system platform of the image version, for example "Windows" or "Linux".
        osVersion:
          allOf:
          - $ref: '#/components/schemas/OsVersion'
          - description: The operating system version of the Amazon EC2 build instance. For example, Amazon Linux 2, Ubuntu 18, or Microsoft Windows Server 2019.
        owner:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The owner of the image version.
        dateCreated:
          allOf:
          - $ref: '#/components/schemas/DateTime'
          - description: The date on which this specific version of the Image Builder image was created.
        buildType:
          allOf:
          - $ref: '#/components/schemas/BuildType'
          - description: <p>Indicates the type of build that created this image. The build can be initiated in the following ways:</p> <ul> <li> <p> <b>USER_INITIATED</b> – A manual pipeline build request.</p> </li> <li> <p> <b>SCHEDULED</b> – A pipeline build initiated by a cron expression in the Image Builder pipeline, or from EventBridge.</p> </li> <li> <p> <b>IMPORT</b> – A VM import created the image to use as the base image for the recipe.</p> </li> </ul>
        imageSource:
          allOf:
          - $ref: '#/components/schemas/ImageSource'
          - description: The origin of the base image that Image Builder used to build this image.
      description: The defining characteristics of a specific version of an Image Builder image.
    ForbiddenException: {}
    CallRateLimitExceededException: {}
    ImageBuilderArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):(?:image-recipe|container-recipe|infrastructure-configuration|distribution-configuration|component|image|image-pipeline|workflow\/(?:build|test|distribution))/[a-z0-9-_]+(?:/(?:(?:x|[0-9]+)\.(?:x|[0-9]+)\.(?:x|[0-9]+))(?:/[0-9]+)?)?$
    OsVersion:
      type: string
      minLength: 1
    Platform:
      type: string
      enum:
      - Windows
      - Linux
    VersionNumber:
      type: string
      pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
    FilterValue:
      type: string
      pattern: ^[0-9a-zA-Z./_ :-]{1,1024}$
    FilterValues:
      type: array
      items:
        $ref: '#/components/schemas/FilterValue'
      minItems: 1
      maxItems: 10
    ImageType:
      type: string
      enum:
      - AMI
      - DOCKER
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/imagebuilder/
x-hasEquivalentPaths: true
